export const BANES = [
  { name: "Blinded", url: "https://openlegendrpg.com/bane/blinded", icon: "icons/banes/test.png" },
  { name: "Charmed", url: "https://openlegendrpg.com/bane/charmed", icon: "icons/banes/test.png" },
  { name: "Deafened", url: "https://openlegendrpg.com/bane/deafened", icon: "icons/banes/test.png" },
  { name: "Death", url: "https://openlegendrpg.com/bane/death", icon: "icons/banes/test.png" },
  { name: "Demoralized", url: "https://openlegendrpg.com/bane/demoralized", icon: "icons/banes/test.png" },
  { name: "Disarmed", url: "https://openlegendrpg.com/bane/disarmed", icon: "icons/banes/test.png" },
  { name: "Dominated", url: "https://openlegendrpg.com/bane/dominated", icon: "icons/banes/test.png" },
  { name: "Fatigued", url: "https://openlegendrpg.com/bane/fatigued", icon: "icons/banes/test.png" },
  { name: "Fear", url: "https://openlegendrpg.com/bane/fear", icon: "icons/banes/test.png" },
  { name: "Forced Move", url: "https://openlegendrpg.com/bane/forced-move", icon: "icons/banes/test.png" },
  { name: "Immobile", url: "https://openlegendrpg.com/bane/immobile", icon: "icons/banes/test.png" },
  { name: "Incapacitated", url: "https://openlegendrpg.com/bane/incapacitated", icon: "icons/banes/test.png" },
  { name: "Knockdown", url: "https://openlegendrpg.com/bane/knockdown", icon: "icons/banes/test.png" },
  { name: "Memory Alteration", url: "https://openlegendrpg.com/bane/memory-alteration", icon: "icons/banes/test.png" },
  { name: "Mind Dredge", url: "https://openlegendrpg.com/bane/mind-dredge", icon: "icons/banes/test.png" },
  { name: "Nullify", url: "https://openlegendrpg.com/bane/nullify", icon: "icons/banes/test.png" },
  { name: "Persistent Damage", url: "https://openlegendrpg.com/bane/persistent-damage", icon: "icons/banes/test.png" },
  { name: "Phantasm", url: "https://openlegendrpg.com/bane/phantasm", icon: "icons/banes/test.png" },
  { name: "Polymorph", url: "https://openlegendrpg.com/bane/polymorph", icon: "icons/banes/test.png" },
  { name: "Provoked", url: "https://openlegendrpg.com/bane/provoked", icon: "icons/banes/test.png" },
  { name: "Spying", url: "https://openlegendrpg.com/bane/spying", icon: "icons/banes/test.png" },
  { name: "Sickened", url: "https://openlegendrpg.com/bane/sickened", icon: "icons/banes/test.png" },
  { name: "Silenced", url: "https://openlegendrpg.com/bane/silenced", icon: "icons/banes/test.png" },
  { name: "Slowed", url: "https://openlegendrpg.com/bane/slowed", icon: "icons/banes/test.png" },
  { name: "Stunned", url: "https://openlegendrpg.com/bane/stunned", icon: "icons/banes/test.png" },
  { name: "Stupefied", url: "https://openlegendrpg.com/bane/stupefied", icon: "icons/banes/test.png" },
  { name: "Truthfulness", url: "https://openlegendrpg.com/bane/truthfulness", icon: "icons/banes/test.png" }
];
